<?php
echo $this->formButton(
    'add',
    sprintf('Create New %s', $definition->options()->display_name),
    array(
        'class' => 'btn large primary',
        'onclick' => sprintf(
            "window.location='%s'",
            $this->url('spiffyadmin/add', array('model' => $model))
        )
    )
);
echo '&nbsp;&nbsp;';
echo $this->formButton(
    'back',
    'Back To List',
    array(
        'class' => 'btn large',
        'onclick' => sprintf(
            "window.location='%s'",
            $this->url('spiffyadmin', array('model' => $model))
        )
    )
);

$columns = array();
foreach($definition->options()->getViewProperties() as $property => $options) {
    $columns[] = array(
        'sTitle'    => $options['label'],
        'mDataProp' => $options['property'],
        'sWidth'    => isset($options['width']) ? $options['width'] : null,
        'sClass'    => isset($options['class']) ? $options['class'] : null,
        'bSortable' => isset($options['sortable']) ? $options['sortable'] : true
    );
}

if ($definition->options()->getCanEdit()) {
    $columns[] = array(
        'sTitle'    => 'Edit',
        'mDataProp' => 'edit',
        'sWidth'    => '10%',
        'bSortable' => false
    );
}

if ($definition->options()->getCanDelete()) {
    $columns[] = array(
        'sTitle'    => 'Delete',
        'mDataProp' => 'delete',
        'sWidth'    => '10%',
        'bSortable' => false
    );
}

echo $this->dataTable(
    'grid',
    array(),
    array(
        'bStateSave'      => true,
        'bJQueryUI'       => true,
        'sPaginationType' => 'full_numbers',
        
        'aoColumns' => $columns,
        
        'aaData' => $data
    )
);