<?php
echo $this->form()->openTag($form);

foreach($form->getElements() as $name => $element) {
    if ($name == 'submit') {
        continue;
    }

    printf('<div class="element %s">', $name);

    echo $this->formLabel()->openTag($element);
    echo ucfirst($name);
    echo $this->formLabel()->closeTag();

    if ($element instanceof \DoctrineORMModule\Form\Element\DoctrineEntity) {
        echo $this->formSelect($element);
    } else {
        echo $this->formElement($element);
    }

    echo $this->formElementErrors($element);

    echo '</div>';
}

$form->get('submit')->setAttribute('class', 'btn btn-success');
?>

<div class="buttons">
    <?=$this->formInput($form->get('submit')) ?>

    <a href="<?=$this->url('spiffyadmin/view', array('name' => $definition->getName())) ?>" class="btn">
        Cancel
    </a>
</div>

<?=$this->form()->closeTag() ?>